import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thread Affair</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="header text-warning">
        HELLO WORLD
        <img src="/images/logo.jpg" alt=""></img>
        <i className="fa-solid fa-phone"></i>
      </header>

      <main className="content">
        <div className="badge">20off</div>
        <div className="badge badge-secondary">new entry</div>
        <div className="badge badge-oversized">%</div>
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
